# Generated by Django 5.2.6 on 2025-09-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-assigned_at']},
        ),
    ]
